### ISSUE TITLE
Omniauth 版本请求

### ISSUE THREAD

**Issue by icbd** [jinhucheung/omniauth-dingding#1]
非常感谢你贡献了这个 Gem, 而且代码组织的也很清晰.

我在使用中遇到了一个问题, 我们既有的系统已经接入了很多 Omniauth 的插件, 遗憾的是他们依赖:

```Gemfile
gem 'omniauth', '~> 1.8'
```

也就是说, 他们跟 `omniauth-dingding` 的 `~> 2.0` 会产生冲突.

不知道您是否愿意降低对 `omniauth` 的依赖版本? (这或许会让更多的既有系统得到支持)

**Comment by jinhucheung** [comment]
@icbd thanks! 已经更新依赖，可使用 `omniauth-dingding` v0.2.0

`omniauth-oauth2` v1.5.0 要求 `omniauth` v1.2 以上，应该满足你们的需求
