### ISSUE TITLE
更名为 DingTalk 的请求

### ISSUE THREAD

**Issue by icbd** [jinhucheung/omniauth-dingding#4]
"钉钉" 的官方英文名称为 "DingTalk". Gem 包中的 `name` 为 `dingding` 虽然不会对广大的终端用户可见, 但是会影响到系统管理员配置的 key. 我们想让这些名字都统一使用 `DingTalk` 和 `ding_talk`.

不知道你是否愿意做这样的调整? 

这很可能会对你既有的系统产生影响, 所以我的备选方案是将当前的代码移植到我们的系统中, 然后做更名操作 (这不是第一选择).

_我的WX: `Cbd-Focus`, 如果您方便的话 😂_

**Comment by jinhucheung** [comment]
@icbd Sorry, 其实在这个 Gem 之前还有另外一个 Gem 支持了钉钉个人第三方应用，已使用 dingtalk namespace
https://github.com/liukun-lk/omniauth-dingtalk

这个 Gem 增加对企业内部应用的支持。

建议做本地化或者 fork :+1:
